# Generated by Django 5.0 on 2025-10-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_notificationpreference_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'User Settings'},
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='achievement_notifications',
            new_name='article_alerts',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='milestone_notifications',
            new_name='chat_notifications',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='profile_public',
            new_name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_id',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='ai_personality',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='ai_response_length',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='language',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='new_article_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_conversation_count',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_reading_history',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='system_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('article', 'New Article'), ('feature', 'New Feature'), ('chat', 'Chat Response'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
